# Generated by Django 4.1.7 on 2023-03-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='name',
            field=models.CharField(default='Canon', max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='camera',
            name='resolution',
            field=models.CharField(default='20MP', max_length=100),
        ),
    ]
